code-dot-org/craft

karma.conf.js
package.json
src/js/game/GameController.js
test/integration/AdventurerTest.js
test/unit/LevelModelTest.js

To run via Chrome: `WATCH=1 npm run test:integration`.

Add skeleton integration test using Karma and Headless Chrome

---

src/js/game/LevelMVC/LevelModel.js
src/js/game/LevelMVC/LevelPlane.js

As the level planes get more complex, I think we'll want better ways to ask questions about the plane without having to use a raw index into the array each time.
Creating a `LevelPlane` class (that for now just extends `Array`) to hold these new convenience methods.

Extract `LevelPlane` class

---

.travis.yml
codecov.yml
hooks/pre-commit

- Add lint pre-commit hook (to enable, upgrade git to 2.9 then run `git config core.hooksPath hooks`).
- Disable Travis CI email notifications.
- Turn on Codecov comments.

Build updates

---

package.json
src/js/game/GameController.js
src/js/game/LevelMVC/LevelBlock.js
src/js/game/LevelMVC/LevelModel.js
src/js/game/LevelMVC/LevelPlane.js
test/integration/AdventurerTest.js
test/unit/LevelPlaneTest.js

Basic track placement following the rules of https://minecraft.gamepedia.com/Rail#Placement.
This PR doesn't yet update surrounding tracks.  That behavior will depend on @WilliamHarmonMS's change to refresh the Action Plane.  For now only the placed track is mutated to the correct sprite.

Dynamic tracks

---

src/js/game/LevelMVC/LevelPlane.js
test/unit/LevelPlaneTest.js

Place the following test pattern, and verify that it matches the expected wire layout:

Add basic redstone wire test coverage

---

src/js/game/GameController.js
test/helpers/DesignerLevels.js
test/helpers/RunLevel.js
test/integration/DesignerTest.js

Follow up to PR https://github.com/code-dot-org/craft/pull/56.

Continue adding test coverage for Events levels

---

codecov.yml

See: https://docs.codecov.io/v4.3.6/docs/fixing-paths

Reduce Codecov root path

---

src/js/game/Entities/BaseEntity.js
src/js/game/Entities/Zombie.js
test/helpers/DesignerLevels.js
test/integration/DesignerTest.js

Follow up to PR https://github.com/code-dot-org/craft/pull/68.

Add Designer level 8 & 9 integration tests

---

src/js/game/LevelMVC/LevelBlock.js
src/js/game/LevelMVC/LevelModel.js

Remove unused

---

src/js/game/LevelMVC/LevelPlane.js

Use the same kind of lookup table we use for minecart tracks.  For a given sprite, look up which variant based on the surrounding sprites:
|  | (empty) | North | South | North & South |
| - | - | - | - | - |
| **(empty)** | "" | "Vertical" | "Vertical" | "Vertical" |
| **East** | "Horizontal" | "UpRight" | "DownRight" | "TRight" |
| **West** | "Horizontal" | "UpLeft" | "DownLeft" | "TLeft" |
| **East & West** | "Horizontal" | "TUp" | "TDown" | "Cross" |
E.g. if you have a North & East & West connection, then the sprite should be `"redstoneWireTUp"` (bottom row, second column).
I verified unit tests are still passing.

Use a lookup table to simplify redstone wire sprite variants

---

src/js/game/Entities/BaseEntity.js
src/js/game/Entities/Sheep.js
src/js/game/Entities/Zombie.js
src/js/game/GameController.js
src/js/game/LevelMVC/FacingDirection.js
src/js/game/LevelMVC/LevelModel.js
src/js/game/LevelMVC/LevelPlane.js
src/js/game/LevelMVC/LevelView.js
src/js/game/LevelMVC/Utils.js
test/unit/LevelPlaneTest.js

Address https://github.com/code-dot-org/craft/pull/96#discussion_r138232605.

Facing direction cleanup

---

src/js/game/LevelMVC/LevelPlane.js

bug introduced by a merge conflict resolution or something

---

src/js/game/Entities/Agent.js

Prevent Agent from trying to collect items

---

src/js/game/GameController.js

Preventing WASD from controlling Agent

decouple agent movement from WASD

---

src/js/game/GameController.js
src/js/game/LevelMVC/LevelView.js

Add Victory Animation for Agent Spawn

---

src/js/game/Entities/Agent.js

Agent needs to not be blocked by steve, just like steve isn't blocked by the agent.
Resolves https://github.com/code-dot-org/craft/issues/205.

agent can now move through Steve

---

test/integration/DesignerTest.js

Disabled in commit https://github.com/code-dot-org/craft/commit/0db5c1f2f351748866b10c47ed4028dc992f4ec6.  Trying to re-enable now!

Re-enable the "Designer 8: Explode Stone Wall" integration test

---

src/js/game/LevelMVC/LevelBlock.js
src/js/game/LevelMVC/LevelPlane.js
test/unit/LevelPlaneTest.js

@joshlory PTAL 
fix for issue [#160](https://github.com/code-dot-org/craft/issues/160)

pressurePlates can no longer be weakly charged

---

src/js/game/GameController.js

Found via the [code coverage report for GameController.js](https://codecov.io/gh/code-dot-org/craft/src/436c74beb4afa0f653154a41cb6d44d081c7f38a/src/js/game/GameController.js). There's more cleanup to do, but starting here for now 😄.

De-duplicate controller code for choosing a target entity

---

src/js/game/GameController.js

stop pushing the Agent

---

test/unit/LevelPlaneTest.js

Unit test for Issue https://github.com/code-dot-org/craft/issues/105.  Test is skipped because it's not passing yet.

Add unit test for curved tracks snapping to newly-placed tracks

---

test/helpers/AgentLevels.js
test/helpers/RunLevel.js
test/integration/AgentTest.js

Add test fixture and integration test for the first Agent level.  The actual level will change, but this is a good baseline to make sure we don't regress pressure plate and Agent behavior.

Initial Agent level integration test

---

src/js/game/Entities/Agent.js

And round and round we go. This time, player always over agent is the new desired direction.

agent now always draws over steve

---

src/js/game/Entities/Agent.js
src/js/game/LevelMVC/LevelView.js
src/test-build-only/levels.js

Fixes https://github.com/code-dot-org/craft/issues/175.

the agent shouldn't make noise when walking over water

---

src/index.html.ejs
src/test-build-only/levels.js

Follow up to PR https://github.com/code-dot-org/craft/pull/250.

Add level select to the Playground

---

src/index.html.ejs

Click the toggle or use the <kbd>Shift</kbd> key to switch targets.  Demo:

Allow the user to switch between controlling the Player & Agent in the Playground

---

src/js/game/Entities/BaseEntity.js
src/js/game/GameController.js
src/js/game/LevelMVC/LevelPlane.js

@joshlory that sure was some gratifying clean up.

doors should no longer close on the agent

---

src/index.html.ejs

Fixes https://github.com/code-dot-org/craft/issues/285.

ascii values don't go up to 868... woops

---

src/js/game/Entities/Chicken.js
src/js/game/Entities/Cow.js
src/js/game/Entities/Creeper.js
src/js/game/Entities/IronGolem.js
src/js/game/Entities/Sheep.js
src/js/game/Entities/Zombie.js
src/js/game/GameController.js
src/js/game/LevelMVC/LevelPlane.js
src/js/game/LevelMVC/LevelView.js

As referenced in https://github.com/code-dot-org/craft/pull/279

Rename LevelView Planes to Groups

---

src/js/game/GameController.js

Fixes https://github.com/code-dot-org/craft/issues/296.

Fix freeze after "use" on an Entity in Agent levels

---

src/js/game/Entities/Agent.js

Follow up to PR https://github.com/code-dot-org/craft/pull/108.  De-duplicate `Agent.prototype.doMoveForward` and `doMoveBackward`.

Remove duplicated Agent code

---

src/js/game/Entities/Agent.js
src/js/game/LevelMVC/LevelBlock.js
test/unit/EntityTest.js

Fix https://github.com/code-dot-org/craft/issues/313

No torches in water

---

src/js/game/Entities/BaseEntity.js
src/js/game/Entities/Player.js
src/js/game/LevelMVC/LevelView.js
test/unit/LevelViewTest.js

Fixes https://github.com/code-dot-org/craft/issues/89

Fix selection indicator to player

---

src/js/game/GameController.js
test/integration/AgentTest.js

@joshlory @Hamms 
Due to feedback, we're looking to change the Agent spawn location at the end of level 1 from above the player to below the player.

new agent spawn location at the end of level 1

---

src/js/game/LevelMVC/LevelView.js
src/js/utils.js

In order to track the Diamond progression path, we need a way to hook in to the collection event.

add craftCollectibleCollected event

---

src/js/game/LevelMVC/LevelPlane.js

Fixes https://github.com/code-dot-org/craft/issues/348.

Refresh neighbor that may affect (or be affected by) a corner shadow

---

src/js/game/LevelMVC/LevelModel.js

@joshlory 
this fixes [issue#358](https://github.com/code-dot-org/craft/issues/358)

placing blocks over a diamondMiniblock would destroy the diamond

---

src/js/game/Entities/BaseEntity.js
src/js/game/LevelMVC/FacingDirection.js
src/js/game/LevelMVC/LevelPlane.js
src/js/game/LevelMVC/Position.js
test/unit/PositionTest.js

Similar to FacingDirection, this class is right now a new place to add common positioning logic helper methods like equivalency and movement that are right now scattered throughout our system.
It's also implemented as a class, which should make it much easier in the future to make the transition from simple `[x, y]` arrays to actual Position instances.

Add Position helper

---

src/js/game/Entities/BaseEntity.js
src/js/game/LevelMVC/LevelModel.js
src/js/game/LevelMVC/LevelView.js

Clean up a handful of methods that can be implemented better now that we have the Position helper

Position cleanup

---

src/js/game/Entities/Agent.js
src/js/game/Entities/BaseEntity.js
src/js/game/Entities/Player.js
src/js/game/GameController.js
src/js/game/LevelMVC/LevelModel.js
test/unit/EntityTest.js

This fixes [issue#367](https://github.com/code-dot-org/craft/issues/367)
Cannot BELIEVE that levelModel.canPlaceBlock() just returned true 😂

trying to place inappropriate blocks would still destroy rails

---

src/js/game/GameController.js

Per Deirdre, use is back in. @joshlory 
@alalb  has more info

use is back per Deirdre

---

src/js/game/Entities/BaseEntity.js
src/js/game/Entities/Player.js
src/js/game/LevelMVC/LevelModel.js
src/js/game/LevelMVC/LevelView.js
test/unit/LevelViewTest.js

@joshlory 
This is, I think, JUST the collecting items while on a rail. Since the 'use' rail riding has been taken out, it's a bit hard to test this at the moment, but [PR#332](https://github.com/code-dot-org/craft/pull/332) fixes that.

just picking up items on rails

---

src/js/game/LevelMVC/LevelBlock.js
src/js/game/LevelMVC/LevelView.js

Fixes https://github.com/code-dot-org/craft/issues/391.

Walkable blocks shouldn't receive block shadows

---

src/js/game/LevelMVC/LevelView.js

Fixes https://github.com/code-dot-org/craft/issues/406.

Don't keep animating if the sprite is no longer in the scene

---

src/js/game/Entities/BaseEntity.js
src/js/game/GameController.js
src/js/game/LevelMVC/AStarPathFinding.js
src/js/game/LevelMVC/LevelModel.js
src/js/game/LevelMVC/LevelPlane.js
src/js/game/LevelMVC/Position.js
test/unit/LevelModelTest.js
test/unit/LevelPlaneTest.js

Also update a few methods that were manually calculating adjacent positions to use the existing helpers. It'll probably be easiest to review this PR commit-by-commit, since each one is for the most part standalone.

Update a bunch of methods to accept single Position arguments, rather than separate X and Y arguments

---

src/js/game/GameController.js

Before playing the placeblock animation, specifically, so that we can
play the appropriate animation.
Fixes https://github.com/code-dot-org/craft/issues/405

For special minecart level, override blockType earlier

---

src/assets/images/Blocks.json
src/js/game/LevelMVC/LevelBlock.js
src/js/game/LevelMVC/LevelView.js

@joshlory 
An invisible block will get shadows and collision behavior. These will be used for the base of the NetherPortal.

adding an invisible block for usre with NetherPortal

---

src/js/game/Entities/BaseEntity.js
src/js/game/GameController.js

moved rail riding handling to entity class, and included a pressureplate handling

handle plate if getting on rails

---

src/js/game/LevelMVC/LevelView.js

All I can think of for [issue424](https://github.com/code-dot-org/craft/issues/424)

this might fix it

---

src/js/game/Entities/BaseEntity.js
src/js/game/LevelMVC/LevelModel.js

Resolves https://github.com/code-dot-org/craft/issues/435.

Fix `moveBackward`

---

src/js/game/GameController.js
src/js/game/LevelMVC/LevelModel.js
test/unit/LevelModelTest.js

@joshlory 
this fixes [issue439](https://github.com/code-dot-org/craft/issues/439)
something broke the actionPlane conflict checking when I ported over everything to placeDirection. So double woops, but I fixed that too.

fixed conflict check for place direction

---

src/js/game/Entities/Ghast.js
src/js/game/LevelMVC/LevelEntity.js
src/test-build-only/levels.js

Ship initial version of PR https://github.com/code-dot-org/craft/pull/414 for launch.  We'll likely re-visit this design tomorrow.

Ghasts next

---

src/js/game/Entities/Ghast.js
src/js/game/LevelMVC/LevelEntity.js
src/test-build-only/levels.js

@joshlory 
Cole and I had some fun. Deirdre was into it. What do you guys think? 😂 
(ghasts are meant to be placed at [1,5] and [7,8] as starting positions. This is a bit hard coded specifically to work with level 11 of 2017 HoC)

Fun with ghasts

---

package.json

Remove istanbul dependency from package.json

---

src/js/game/LevelMVC/AssetLoader.js

Fix black squares on https://studio.code.org/s/minecraft/stage/1/puzzle/12 in some browsers.

Designer also uses WaterAO and LavaGlow assets

---

package.json

Thank you @madelynkasula for finding & tracking down a fix!

Lock to webpack 4.19

---

demo/index.html
src/js/game/LevelMVC/LevelView.js

Reverts code-dot-org/craft#486

Revert "Smooth prismarine block alpha transition"

---

src/js/game/LevelMVC/LevelBlock.js
src/js/game/LevelMVC/LevelView.js

Adds:
- Underwater magma
- Bubble column
- Conduit
- Chiseled stone bricks

Additional block types

---

demo/index.html
src/js/game/LevelMVC/LevelView.js

Resolves https://github.com/code-dot-org/craft/issues/480.

Update prismarine to use a shared texture, fade between frames

---

src/assets/images/entities/Sea_Turtle_2018.json
src/js/game/Entities/SeaTurtle.js

Minecraft | Fixed the turtle animation

---

src/js/game/GameController.js
src/js/game/LevelMVC/Utils.js

Sample usage — to place an entity below where the player is currently standing, and jump up:
```js
gameController.codeOrgAPI.placeBlock(null, "boat", "Player");
```

Allow `placeBlock` to also place entities

---

src/js/game/Entities/BaseEntity.js
src/js/game/Entities/Player.js
src/js/game/LevelMVC/LevelView.js

Follow up to PR https://github.com/code-dot-org/craft/pull/513.
Resolves https://github.com/code-dot-org/craft/issues/524.

Fix up animation reference for turns and other actions

---

src/js/game/LevelMVC/LevelBlock.js
src/js/game/LevelMVC/LevelModel.js

Bubble column should be transparent for FoW calculation

---

src/js/game/LevelMVC/LevelModel.js

Fixes https://github.com/code-dot-org/craft/issues/455.

Avoid collisions in emissive cache

---

src/js/game/GameController.js

This makes keyboard input move the player if anything other than `<input>` or `<textarea>` are selected

Make editableElementSelected more specific
