package.json, test/integration/AdventurerTest.js
Seeing some minor changes in code coverage when I wouldn't expect anything to change.  The lines are entity animations that run after delaying a random number of seconds.  Try stubbing `Math.random()` to return a consistent value to reduce variance.
=> Reduce variance in code coverage metrics due to random animation timing

.travis.yml, Gruntfile.js, package.json
Start serving the most recent build at https://code-dot-org.github.io/craft/.  This will show the same development page as running `grunt` locally (see [README.md](https://github.com/code-dot-org/craft/blob/master/README.md#setup-your-project)).
=> Add Travis CI deploy step for publishing to GitHub Pages

src/js/game/GameController.js, src/js/game/LevelMVC/LevelModel.js, src/js/game/LevelMVC/LevelPlane.js, src/js/game/LevelMVC/LevelView.js
Fixes a few remaining issues:
- Newly-placed blocks have the correct shadow.
- Don't jump up a block height when placing redstone wires.
- Fix stale sprites after destroying redstone wires.
- Prevent double-updating the view in `playPlaceBlockInFrontAnimation`/`playPlaceBlockAnimation` followed by `setBlockAt`.
After this PR I think we're ready to ship!
=> Dynamic redstone: ship-readiness changes

src/js/game/Entities/BaseEntity.js, src/js/game/GameController.js, test/helpers/DesignerLevels.js, test/helpers/RunLevel.js, test/integration/DesignerTest.js
All tweens and animations are played at different speeds controlled by the `customSlowMotion` param. However the `wait` block and the small pauses in Creeper animations are controlled by setTimeout. Take into account the timeScale, so when running faster or slower these pauses are adjusted by the correct amount.
=> Add Designer level 7 integration test, also scale `wait` by timeScale

src/js/game/LevelMVC/LevelView.js, src/test-build-only/levels.js
Use `onAnimationEnd` instead of `onComplete` to play minecart animation.  Fixes jumps in playback when running `LevelView.prototype.playTrack` with more than 1 turn.
=> Minecart animation fix

src/js/game/Entities/Player.js, src/js/game/GameController.js, src/js/game/LevelMVC/LevelView.js
The Agent character will have different default offsets than the player.  Extract a `positionToScreen` helper so the x and y offsets all live in one place.
There should be no functional difference from this change.
=> Cleanup player offset magic numbers

src/js/game/Entities/BaseEntity.js, src/js/game/Entities/Player.js, src/js/game/GameController.js, src/js/game/LevelMVC/AStarPathFinding.js, src/js/game/LevelMVC/LevelModel.js, src/js/game/LevelMVC/LevelPlane.js, src/js/game/LevelMVC/LevelView.js, test/unit/LevelPlaneTest.js
This was causing problems during the ES5 transpile.  More details here: http://perfectionkills.com/how-ecmascript-5-still-does-not-allow-to-subclass-an-array/
For now I updated everything as-is to avoid introducing new issues.  There are a bunch of places we're reaching directly in to `actionPlane._data`.  We should clean up some of those to use `getBlockAt` in a future PR!
=> Don't inherit from Array

src/js/game/LevelMVC/LevelView.js
Fixes running Adventurer 13 a second time, after the cut scene animation has finished.
=> Reset should move the camera to start position (when not following)

src/js/game/Entities/BaseEntity.js, src/js/game/Entities/Player.js, src/js/game/GameController.js, src/js/game/LevelMVC/AStarPathFinding.js, src/js/game/LevelMVC/LevelModel.js, src/js/game/LevelMVC/LevelPlane.js, src/js/game/LevelMVC/LevelView.js
In response to https://github.com/code-dot-org/craft/pull/99
Added a `getAllPositions` method for operations which want to examine all blocks on a plane, and updated everything to use `getBlockAt` positional access rather than index access.
Note that this required updating in a couple of places the way we're approaching an operation, and in a couple of other places it requires awkwardly converting indexes to positions. I think for the former considerations all the changes resulted in improved code, and in the latter consideration it serves to highlight the fact that we would probably prefer to be using positions more universally.
=> Add levelPlace._data access methods

src/js/game/LevelMVC/LevelModel.js, src/test-build-only/levels.js
1. The definition of the test level was invalidly using a 10x11 grid for
_only one_ plane. All plane definitions need to be the same dimensions;
removed the offending row.
2. The agent placement logic was attempting to call a block function
that does not exist; renamed isEmptyOrEntity to getIsEmptyOrEntity
=> Fix two bugs preventing the playground from loading

src/js/game/LevelMVC/LevelBlock.js, src/js/game/LevelMVC/LevelView.js, test/unit/LevelBlockTest.js
Levelbuilders can now add miniblocks that appear at level initialization, and which will be collected by the player just like other collectables:
Two things to note:
First, the default range for collectables is pretty large; the feature this functionality is desired for involves adding diamonds to levels to give the player an extra challenge, and it would probably be nice for that to have a more restrictive area. (but that's an issue for a separate PR)
Second, to enable this on levelbuilder, we simply need to add the appropriate strings to the set of block options for the level:
```
diff --git a/dashboard/app/models/levels/craft.rb b/dashboard/app/models/levels/craft.rb
index 6a551e026f..b8300b3cc5 100644
--- a/dashboard/app/models/levels/craft.rb
+++ …
```
=> add support for miniblocks in level specification

src/js/game/Entities/Agent.js, src/js/game/Entities/Player.js, src/js/game/GameController.js, src/js/game/LevelMVC/LevelModel.js, src/js/game/LevelMVC/LevelView.js, test/unit/LevelModelTest.js
This is necessary to enable the `isAgentLevel` setting to distinguish from `isEventLevel`
=> add getIsDirectPlayerControl helper to replace isEventLevel for character movement logic

src/js/game/LevelMVC/LevelView.js
Looks like when we generalized the animation generation, one animation got left hardcoded to South, resulting in the player idle animation eventually turning the player to _appear_ as if they were facing south, no matter which direction they are actually facing.
The fix is fortunately simple
=> fix player idle animation to not always face south

src/js/game/LevelMVC/LevelView.js
fixes #150
fixes #147
fixes #145
fixes #144
fixes #137
fixes #126
=> Handle destroying a blockType with no associated miniblock

src/js/game/GameController.js
Pressure Plate (and iron door double-checking) was enabled only for directional movement, not for the Forward/Backward movement that the Agent uses.
(As an aside, Agent in the 2-D Craft Playground dev test environment _is_ using directional movement, which is why this bug went unnoticed)
Fixes https://github.com/code-dot-org/craft/issues/154
=> Agent can trigger pressure plates

src/js/game/GameController.js
@joshlory @Hamms PTAL
this was causing a crash when players 'use' facing off the map.
=> IMPORTANT: crash fix

src/js/game/GameController.js, src/js/game/LevelMVC/LevelModel.js
doAgentSpawn() is probably a bit messy. If the level is an agent level, doAgentSpawn() is called at init with a passed in levelData so you get the normal behavior. If you call it manually on a non-agent level, with a first argument of null, you spawn the agent at the index you passed in.
I've got ideas about how to clean this up, but also welcome any input you guys might want.
=> for level 1, we need to be able to spawn an agent on solutionCheck()

src/js/game/Entities/Agent.js, src/js/game/Entities/BaseEntity.js, src/js/game/LevelMVC/LevelView.js
Implemented by adding a `canMoveThrough` method to entities (which agent overrides), specifying whether or not other entities can move through them.
Also added a `getSortOrderOffset` method for retrieving the sort order offset (which agent also overrides), rather than hardcoding `5` everywhere.
Note that you should probably view the diff [with withspace ignored](https://github.com/code-dot-org/craft/pull/120/files?w=1) as I also fixed some weird whitespace in BaseEntity
=> player (and other entities) should be able to move through agent

src/js/game/LevelMVC/LevelView.js
This is causing crashes when players try and get diamond blocks.
=> URGENT FIX: crash on refreshActionPlane + diamondMiniblock

src/js/game/GameController.js, src/js/game/LevelMVC/LevelView.js
Previously, when "destroy block" was called when the agent had no block
to destroy, we were defaulting back to calling the _player_ version of
the "punch the air" animation, rather than the _agent_ version.
=> Allow agent to punch air

src/js/game/Entities/BaseEntity.js
Resolves https://github.com/code-dot-org/craft/issues/210.
Before: (hard to see in the gif, but the Redstone and Rail tiles south of the entity fade out when the player walks one grid north of the tile)
After: (no fade)
=> Don't fade transparent blocks when an entity stands to the north

src/js/game/Entities/Player.js, src/js/game/LevelMVC/LevelView.js
We have slightly different requirements for Diamond miniblocks than we do for the standard miniblocks dropped when destroying other blocks. Namely, we want the collectible range to be quite a bit smaller, so you have to actually land on the diamond's square to collect it, and we also want the randomized drop location to be a bit less variable, so it's guaranteed to always be visually obvious which square the diamond is actually on.
This PR represents one such approach to implementing those requirements. Another way to do it would be to override miniblock behavior for all of agent, so that the miniblocks defined at level-creation time behave exactly the same as standard miniblocks. This would have the advantage of a more consistent user experience, but I think that having these diamonds be …
=> Add some tweaks to diamond progression path

src/js/game/LevelMVC/LevelView.js
Prevents piston arm shadows from drawing on top of actionPlane blocks.
=> piston arm shadows no longer overlay over actionPlane blocks

src/js/game/LevelMVC/LevelView.js
=> Support blocks that believe they should drop a miniblock, but for which the level view has no mini block frame data

src/index.html.ejs
Make it possible to place more blocks in the playground from the dropdown menu.
=> Add redstone torch, pressure plate & pistons to the playground

src/js/game/Entities/Player.js, src/js/game/GameController.js
This is something we want to try out for the next in-classroom test.  It would allow the Player to explore the level before the student decides to run the Agent code.  They'll still need the Agent's help to solve the puzzle, but they can experiment with pressure plates etc. to see what they control before writing code to solve the puzzle.
=> In Agent levels, allow the Player to move as soon as the game loads

src/js/game/Entities/Agent.js
The player has a slight delay when in block-movement mode; because when
in arrow-movement mode the delay is handled by the arrows, we don't
impose an additional delay.
Because the agent was derived from player code, it was erroneously
giving itself no delay when the _player_ was in arrow mode.
Re-added the delay, independent of the state. Also gave it a delay of
about 2/3 that of the player to represent the fact that the agent should
still be moving slightly faster
Before
After
=> Add slight delay to Agent movement

src/js/game/Entities/BaseEntity.js, src/js/game/Entities/Sheep.js, src/js/game/Entities/Zombie.js
Start to use inherited methods from `BaseEntity` where possible.
=> De-duplicate inherited entity methods

src/js/game/LevelMVC/LevelBlock.js, src/js/game/LevelMVC/LevelPlane.js, test/unit/LevelPlaneTest.js
@joshlory @Hamms 
This is a fix for [issue#265](https://github.com/code-dot-org/craft/issues/265)
=> sticky pistons won't grab the wrong objects now

src/js/game/Entities/Agent.js, src/js/game/Entities/Player.js, src/js/game/LevelMVC/LevelView.js
[First](https://github.com/code-dot-org/craft/commit/8b52ea2aceae19688bf2e4ef1649dfc34cf90908), I update the `playMoveForwardAnimation` and `playMoveBackwardAnimation` methods to significantly reduce the amount of repeated code between them.
[Second](https://github.com/code-dot-org/craft/commit/94292a7f0b5089e61d2ee57360623a88438c86b2), I update the walk animation to actually hook into the tween and update the entity sortOrder at (approximately) the halfway point of the animation, rather than always updating it at the beginning. This means that the nice walking overlap effect happens for both entities in both directions, rather than before where it would only happen for the entity being drawn on the "bottom"
Entity | Before | After
--- | --- | ---
Agent | …
=> Update sortOrder Index during movement animation, rather than before

src/js/game/LevelMVC/LevelView.js
Partial fix for https://github.com/code-dot-org/craft/issues/164#issuecomment-335968741.  Currently we only correct piston sort order for newly-placed blocks.  Also correct piston sort order for blocks in the level config.
Before:
After:
=> Correct piston sort order for blocks in the level config

src/js/game/LevelMVC/LevelBlock.js, src/js/game/LevelMVC/LevelView.js
Blocks that conceptually lie flat on the ground have up til this point not been able to receive shadows from other blocks nor from the ShadeLayer that applies to all ground blocks. Now they can!
Specifically, blocks now have an internal concept of whether or not they are "flat", and whether or not they should be rendered on the ground layer. LevelView also now supports paying attention to this, and rendering Action blocks on either the action or ground layer.
Note that we have both a LevelModel.actionPlane and a LevelView.actionPlane, which are two different things, and this PR makes that even more confusing. I plan to (in a separate PR) rename LevelView.actionPlane to LevelView.actionGroup to help reduce this confusion.
=> Render "flat" blocks in Ground Plane

src/js/game/LevelMVC/LevelView.js
The Ground Plane uses ["Shade_Layer.png"](https://github.com/code-dot-org/craft/blob/b7a639891326a1a054280e865de5501353cda91a/src/assets/images/Shade_Layer.png) to provide some visual variation and make the grid square visible.  Add similar variation to the Action Plane.
Before:
After:
=> Add some visual variance to the Action Plane, to match Shade_Layer.png

src/js/game/LevelMVC/LevelView.js
Because `refreshGroundGroup` is now partially responsible for populating LevelView's `actionPlaneBlocks` array, when refreshing the action group we don't want to reset `actionPlaneBlocks` until after refreshing the ground group. And because blocks are no longer added to the array strictly in order (because we add all ground blocks first in the `refreshGroundGroup` method before going in and adding the action blocks), it no longer makes sense to use `.push` to update the array.
And finally, since we're no longer using `.push`, the creation of the blocks that happens in `refreshGroups` is now practically identical to the creation of blocks that happens in the `createActionPlaneBlock` helper method, so just use that instead of any custom logic.
=> Fix ground group refresh bug

src/js/game/LevelMVC/LevelPlane.js
@joshlory or @Hamms 
Goofed and didn't check bounds. setBlockAt() calls coordinatesToIndex() which assumes everything is in bounds, and it ends up wrapping: [-1, 3] is interpreted as [9, 2] (because y * width + x, if x is -1 you just end up with 30 - 1 = 29)
Completely happenstance that it wrapped perfectly to the row above. This was breaking the diamond path in level 5, but should be fine now.
Resolves https://github.com/code-dot-org/craft/issues/288.
=> woooops. We weren't checking bounds for off-map-block-pushing

src/js/game/LevelMVC/LevelBlock.js, src/js/game/LevelMVC/LevelView.js
Updates redstone (and rails) to no longer erroneously display the cube-shaped destroy overlay animation upon destroy, and to instead just immediately explode with no animation.
Also update the color of the redstone explosion animation to be dark or bright red depending on whether or not it was powered.
Fixes https://github.com/code-dot-org/craft/issues/80
=> Redstone destroy fixes

src/js/game/LevelMVC/LevelBlock.js, src/js/game/LevelMVC/LevelModel.js
Fixes https://github.com/code-dot-org/craft/issues/290.
It looks like "bedrock" was mistakenly classified as an entity block in PR https://github.com/code-dot-org/craft/pull/153.
=> Bedrock should cast shadows

src/js/game/LevelMVC/LevelView.js
fixes issue: [#209](https://github.com/code-dot-org/craft/issues/209)
=> iron doors no longer set player animation to idle

src/js/game/LevelMVC/LevelView.js
Collectible minblocks were rendering with the actionGroup yOffset being
taken into account, but were not including that offset when saving
themselves to collectibleItems, meaning that the distance calculations
ultimately being used to determine whether or not the player is close
enough to pick them up were off by just that much.
Fixes #319
=> Save correct miniblock offset

src/js/game/LevelMVC/LevelView.js
Resolves https://github.com/code-dot-org/craft/issues/321.  Sample usage:
```js
gameController.levelView.drawHintPath([[5, 9], [5, 7], [6, 7], [6, 5]]);
```
=> Add `levelView.drawHintPath` API for more specific in-game hints

src/js/game/LevelMVC/LevelView.js
Some recently-added blocks were added with keys matching their `Blocks.json` identity, but we actually want them to be keyed by the values [as defined in levelbuilder](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/levels/craft.rb#L74).
Partial fix for https://github.com/code-dot-org/craft/issues/222
=> update some block names to match levelbuilder

src/js/game/Entities/Agent.js, src/js/game/LevelMVC/LevelBlock.js
@joshlory PTAL
This fixes [issue:318](https://github.com/code-dot-org/craft/issues/318)
pressurePlates should be fine to place on land (and therefore on the action Plane) but NOT over water, thus in the ground plane, thus allowing the player to put redstoneWire over top of them. 
What a silly mistake 😥
=> can not put pressure plates on land but not in water/lava

src/js/game/LevelMVC/LevelBlock.js
So that we can take advantage of the isRail flag, which we were formerly trying to check on the `blockType` string rather than on an actual block
=> Update static isFlat method to reference instance, rather than vice versa

src/js/game/LevelMVC/FacingDirection.js, src/js/game/LevelMVC/LevelPlane.js, test/unit/LevelPlaneTest.js
This allows for newly placed rail blocks to "heal" rails whose
connections were removed, while still not updating rails that are
already happily connected
Fixes https://github.com/code-dot-org/craft/issues/105
=> When rail blocks are removed, sever the connections from adjacent rail blocks

src/js/game/GameController.js
@joshlory 
if we're in an agent level, the 'use' command should be exited out of. This feature was requested this morning as the direction people want to go with in regards to that functionality.
=> if on an agent level, 'use' command simply exits out

src/js/game/Entities/Ghast.js
@joshlory or @Hamms 
Per Cole and Joel, it has been decided that the best way to handle the Ghast, as it is a flying entity, is to simply have it draw on top of all other sprites and to allow the agent and steve to walk through it.
=> Ghast sprite sort order set to max, so it always draws on top

src/js/game/LevelMVC/LevelView.js
Appears to have regressed here: https://github.com/code-dot-org/craft/commit/4612bdf8d05ed9dbbf30035d598c05e06d4325bb#diff-894dfbadc994764b5b510d470f495021R912
=> Fix typo in the name of the "MiningParticles" animation frames

src/js/game/LevelMVC/LevelModel.js, src/js/game/LevelMVC/LevelPlane.js, test/unit/LevelPlaneTest.js
Replace the old recursive approach to redstone propagation with one
using the new concept of adjacency sets.
Next step is to implement a more targeted refresh operation that only
touches blocks in the adjacency set of the thing being updated, rather
than the whole plane.
=> First pass at refactoring redstone propagation

src/js/game/LevelMVC/LevelModel.js, src/js/game/LevelMVC/LevelPlane.js, test/unit/LevelPlaneTest.js
A while ago, we somehow messed up the method signature for the LevelPlane constructor; we were passing in both an `isActionPlane` flag and a `planeType` string (the latter of which is used by the `levelPlane.isActionPlane()` method). We were also for some reason in LevelModel passing in `levelModel.controller` in place of the `isActionPlane` flag.
I've removed the flag and updated the calls in LevelModel and LevelPlaneTest appropriately.
Given that the LevelModel was passing in a truthy value (the controller) for every plane's `isActionPlane` value, next step is to verify that the check we're doing [here](https://github.com/code-dot-org/craft/compare/fix-levelPlane-constructor?expand=1#diff-2365f8601c9dbb7d718e03c8a23baffcR60) is in fact useless
=> Fix levelPlane constructor

src/js/game/LevelMVC/LevelBlock.js
I'm not sure why glass was made un-breakable, as that doesn't make a ton of sense, but this change -doesn't- break integration tests in any way. Since it doesn't seem to break previous years in any way, I'm looking to fix[ issue 411](https://github.com/code-dot-org/craft/issues/411)
=> can now break glass

src/js/game/LevelMVC/LevelBlock.js, src/js/game/LevelMVC/LevelView.js
@joshlory or @Hamms 
Phaser can crop the destruction animation! Hurrah!
This crops the destruction overlay to the top 40x40 and then scoots it down 20 pixels so that it lines up over the index the player is destroying so that it can appropriately cover "flat" objects that need an overlay (basically only pressurePlates and rails).
this fixes [issue397](https://github.com/code-dot-org/craft/issues/397)
=> phaser CAN crop

src/assets/images/AO.json, src/assets/images/Block_Shadows.json, src/assets/images/LavaGlow.json, src/assets/images/WaterAO.json, src/js/game/LevelMVC/LevelView.js
Right now we offset sprites in the atlas JSON, then again in the code.  This PR combines these two offsets and bakes them into the atlas JSON, so no additional adjustment is needed in code.
In the process I found that the `AOeffect_Left` shadow was off by 1px to the east.  Before:
Fixed:
=> Bake AO offsets into the atlas JSON

src/js/game/GameController.js
Added in 77641b6, we handle movement in Edge differently than in all other browsers. This exception is indirectly responsible for #422, and removing it not only fixes that bug but makes this behave the same in all browsers.
I unfortunately don't know why we added it in the first place, and so I can't be certain that removing it is desirable. @joshlory, thoughts?
=> Remove exceptions for Edge in movement listeners

src/js/game/GameController.js, src/js/game/LevelMVC/LevelBlock.js, src/js/game/LevelMVC/LevelModel.js
This fixes the bugs with Agent placeDirection:
(1) Agent placeDirection was replacing other blocks in the Action Plane [issue445](https://github.com/code-dot-org/craft/issues/445)
(2) Agent placeDirection was placing sand/gravel in the wrong plane when over water [issue446](https://github.com/code-dot-org/craft/issues/446)
These should both be fixed with this PR.
@joshlory
=> Agent placeDirection bugged behavior

src/js/game/LevelMVC/LevelView.js
Fixing the trello issue:
https://trello.com/c/sNi5uJWW/130-level-2-bug-with-door-to-solve-the-puzzle-cant-walk-through-even-though-it-is-open
=> door animation walkability could be desynched

src/js/game/LevelMVC/LevelView.js
@joshlory  or @Hamms 
Apparently there is a crash when the user:
(1) is riding a rail that leads them right up against the edge of the map (so that the "next index" would be out of bounds)
AND
(2) you destroy the final rail segment after they've begun moving to it (cleared the "next rail" being valid check) but the segment is destroyed by the Agent before the player reaches that index
Whackiness but... it's definitely a bounds check on nextPos there. Figured I'd throw in a bounds check for currPos as well because who knows? Should be impossible but that'll be extra safe.
=> bounds checking crash on rail riding

src/js/game/Entities/BaseEntity.js, src/js/game/Entities/Chicken.js, src/js/game/Entities/Cow.js, src/js/game/Entities/Creeper.js, src/js/game/Entities/Ghast.js, src/js/game/Entities/IronGolem.js, src/js/game/Entities/Player.js, src/js/game/Entities/Sheep.js, src/js/game/Entities/Zombie.js, src/js/game/GameController.js, src/js/game/LevelMVC/AStarPathFinding.js, src/js/game/LevelMVC/LevelModel.js, src/js/game/LevelMVC/LevelPlane.js, src/js/game/LevelMVC/LevelView.js, src/js/game/LevelMVC/Position.js, test/integration/AdventurerTest.js, test/integration/AgentTest.js, test/integration/DesignerTest.js, test/integration/FunctionalityTest.js, test/unit/LevelViewTest.js, test/unit/PositionTest.js
new Position instances will have both `instance.x, instance.y` AND
backwards-compatible `instance[0], instance[1]` access options, with the
intention of removing the latter once we can be confident all `[x, y]`
position arrays in the system have been replaced with actual Position
instances.
Note that even with this accomodation, Position instances are not
iterable, so things like `let [x, y] = position` will not work.
General plan of attack for this work-in-progress PR:
=> Add ability to create Position instances

test/unit/LevelModelTest.js
There is for some reason a LevelModel unit test in [the main code-dot-org repo](https://github.com/code-dot-org/code-dot-org/blob/0b45e7553cbbc9c73dc034551fd2afc18cbf8502/apps/test/unit/craft/LevelModel.js) that really should live in this repo
=> add LevelModel tests from main code-dot-org repo

src/js/game/API/CodeOrgAPI.js, src/js/game/CommandQueue/BaseCommand.js, src/js/game/CommandQueue/CallbackCommand.js, src/js/game/CommandQueue/CommandQueue.js, src/js/game/CommandQueue/MoveDirectionCommand.js, src/js/game/CommandQueue/MoveForwardCommand.js, src/js/game/GameController.js
Needed to make these native-is-async in the JS Interpreter.  Even those these functions take a second or so to execute, the JS Interpreter can treat them as synchronous, pausing execution until the callback is called.
=> Add callback for when moveForward() and turn() finish

demo/index.html, src/js/game/LevelMVC/LevelView.js
Fixes #480.
We wanted the prismarine block tweens to subtly change color, so this uses a yoyo'd `.to` transition rather than changing step-wise.
(forgive the dimensions on this gif...)
I set the transition alpha to 0.5, but let me know if that's too drastic of a change!
=> Smooth prismarine block alpha transition

.eslintrc.js, test/integration/AquaticTest.js, test/integration/DesignerTest.js
Progress on #494: Change ESLint configuration to allow async/await syntax (which we determined yesterday is already supported by your Babel configuration).
Updates a couple of tests from my previous PR to illustrate.
=> Configure ESLint to allow async/await

src/js/game/API/CodeOrgAPI.js, test/integration/DesignerTest.js
Extends the `startAttempt` method to return a promised success value, allowing us to `await` it in tests instead of using a wrapper promise and yet-another-nested-callback.
=> Use async/await more in tests

src/js/game/API/CodeOrgAPI.js
In the final puzzle, students will be able to place underwater entities. I went to define the new spawn block and realized I could only access `api.spawnEntity()` for spawning entities in imprecise locations. `api.spawnEntityAt()` is needed to allow us to create a block that will enable users to place entities anywhere. 
Not sure whether there's any test coverage needed for these API changes? All I could find was an integration test for `spawnEntity()` from the Designer tutorial.
=> Add spawnEntityAt API for use in final Aquatic puzzle

demo/demo.js, src/js/game/API/CodeOrgAPI.js, test/integration/AdventurerTest.js, test/integration/AgentTest.js, test/integration/FunctionalityTest.js
Fixes #494. Follow-on to work in https://github.com/code-dot-org/craft/pull/495 and https://github.com/code-dot-org/craft/pull/498.
Applies new async/await pattern to all integration tests, completely removing the internal dependency on the `onAttemptComplete` callback argument to `startAttempt`.  However, I'm not entirely removing this argument yet - it's part of a public API and is still used in the main `code-dot-org/code-dot-org` repo.
=> Move all integration tests to new async pattern

src/js/game/LevelMVC/LevelView.js
=> Minecraft | OverOverlay will now scale correctly to 20x20
